### ISSUE TITLE
Test failures on OSX

### ISSUE THREAD

**Issue by andig** [reactphp/stream#111]
~/htdocs/react-stream master
	❯ phpunit
	PHPUnit 5.5.4 by Sebastian Bergmann and contributors.

	............SSS.SSS.SSS.SSS.SSS.SSS.SSSFSSS.SSS.SSS............  63 / 154 ( 40%)
	............................................................... 126 / 154 ( 81%)
	...........................S                                    154 / 154 (100%)

	Time: 3.6 seconds, Memory: 69.23MB

	There was 1 failure:

	1) React\Tests\Stream\DuplexResourceStreamIntegrationTest::testReadsMultipleChunksFromProcessPipe with data set #0 (Closure Object (...), Closure Object (...))
	Failed asserting that two strings are equal.
	--- Expected
	+++ Actual
	@@ @@
	-'abc'
	+'-n a
	+-n b
	+-n c
	+'

	/Users/andig/Documents/htdocs/react-stream/tests/DuplexResourceStreamIntegrationTest.php:263

	FAILURES!
	Tests: 154, Assertions: 228, Failures: 1, Skipped: 31.

**Comment by cboden** [comment]
Can confirm same results on macOS 10.12.6 w/ PHP v5.6.30

**Comment by andig** [comment]
I will add osx travis coverage once it has been merged in socket to reproduce the final setup.

**Comment by clue** [comment]
The above test basically means that executing `echo -n test` will actually echo `-n test` for Mac OS X while test assumes `-n` is interpreted as an option flag. Let me look into this :shipit:
