### ISSUE TITLE
Unable to write to stream: fwrite(): send of 8192 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by andreybolonin** [reactphp/stream#125]
`11:19:34 ERROR     [websocket] Connection error occurred Unable to write to stream: fwrite(): send of 8192 bytes failed with errno=32 Broken pipe in /var/www/awex.com.ua/vendor/react/stream/src/Buffer.php line 121 ["connection_id" => 10862,"session_id" => "456846955a323dee318b1236559306","client" => "anon-456846955a323dee318b1236559306"] []`

```
"require": {
        "php": ">=7.1",
        "ext-intl" : "*",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-fixtures-bundle": "^2.3",
        "doctrine/doctrine-migrations-bundle": "^1.2",
        "doctrine/orm": "^2.5",
        "gos/web-socket-bundle": "^1.8",
        "gregwar/captcha-bundle": "^2.0",
        "h4cc/wkhtmltopdf-amd64": "^0.12.3",
        "h4cc/wkhtmltopdf-i386": "^0.12.3",
        "incenteev/composer-parameter-handler": "^2.0",
        "knplabs/knp-paginator-bundle": "^2.6",
        "knplabs/knp-snappy-bundle": "^1.5",
        "kwn/number-to-words": "^1.3",
        "misd/phone-number-bundle": "^1.2",
        "phpoffice/phpexcel": "^1.8",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^4.0",
        "sonata-project/admin-bundle": "^3.23",
        "sonata-project/doctrine-orm-admin-bundle": "^3.1",
        "stof/doctrine-extensions-bundle": "^1.2",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/symfony": "^3.4",
        "twig/extensions": "^1.5",
        "twig/twig": "^1.0||^2.0",
        "yadelivery/name-case-lib": "^1.1"
    },
```

`PHP 7.1.12-1 (cli) (built: Nov 29 2017 10:01:08) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.12-1, Copyright (c) 1999-2017, by Zend Technologies`

```
"name": "react/stream",
"version": "v0.4.6",
```

```
"name": "react/socket",
"version": "v0.4.6",
```

**Comment by clue** [comment]
It looks like you're using an outdated version of this component, can you try updating to the latest version?

Without further details, it's a bit hard to diagnose this. It looks like your server is trying to write to a connection that has been closed on the client side. This it not a fatal issue and after emitting an `error` event, the server should automatically `close()` the connection.

I hope this helps :+1:

**Comment by IlhomjonMuxtorov** [comment]
I have problem:
 Unable to write to stream: fwrite(): Send of 205 bytes failed with errno=32 Broken pipe
File: ../vendor/react/stream/src/WritableResourceStream.php
Line: 140

"react/socket": "^1.9"
