### ISSUE TITLE
How to clear console with stream

### ISSUE THREAD

**Issue by Juanperezc** [reactphp/stream#130]
Hi, I'm doing a program with childprocess and stream. and at some point I want to clean the console to load new data in the console, I will try doing a simple command with childprocess but I think there must be another method within stream to clean the console.

**Comment by clue** [comment]
Hi @Juanperezc! I'm not sure I follow what you're trying to do and what your issue is, as it's a bit unclear what you're trying to achieve from the description you've posted.

May I ask you provide a simple gist of what you're trying to achieve? Thanks!

**Comment by Juanperezc** [comment]
Hi @clue , I just want to clean the console to load new data with a command. I was thinking of doing it with a childprocess and execute the "clear" command but I think there must be a better way to do it

**Comment by clue** [comment]
I'm still not sure I follow, maybe you're looking for ANSI/VT100 terminal control characters to clear your terminal?

In this case, `$stdio->write("\x1B[2J");` may help.

Otherwise, can you provide some pseudo code for what you're trying to do?

**Comment by Juanperezc** [comment]
Using what you told me clears the screen but the text cursor remains in the same position.

what I want is to clean the console and have the cursor put on the start
something like if you run "clean" on your console and delete all the text that is in it and is clean to rewrite it

`<?php

$stdin = new \React\Stream\ReadableResourceStream(STDIN, $loop);
$stdout = new \React\Stream\WritableResourceStream(STDOUT, $loop);
$composite = new \React\Stream\CompositeStream($stdin, $stdout);

$composite->on('data', function ($chunk) use ($composite) {
    switch(trim($chunk)){
        case 'clear':{
            $composite->write("\x1B[2J");
            break;
        }
        default: {
        $composite->write('Error not comand found: ' . $chunk);
        }

    }
});`

**Comment by clue** [comment]
Happy to hear this helps! I would suggest reading up on ANSI/VT100 escape sequences if you want to modify your terminal state, as this is otherwise out of scope for this project.

For example, you can use the `<ESC>[{ROW};{COLUMN}H` byte sequence to control the current cursor position.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this persists and we can reopen this :+1:

**Comment by Juanperezc** [comment]
I found the solution .

`$composite->write("\x1B[2J\x1B[0f");`
