### ISSUE TITLE
Unable to write to stream: fwrite(): send of XXX bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by Dju33** [reactphp/stream#135]
Hi everyone,

I have this error with my websocket : 

> Unable to write to stream: fwrite(): send of 243 bytes failed with errno=32 Broken pipe

this appends a lot and I don't know how to solve it...I googled it but find nothing...so I really need your help.

Here my version : 

```
ratchet/pawl   v0.3.1
ratchet/rfc6455  v0.2.3
react/cache  v0.4.2
react/dns v0.4.13
react/event-loop  v0.4.3
react/promise v2.5.1
react/promise-timer  v1.2.1
react/socket  v0.8.10
react/stream  v0.7.7 
```

PHP 7.1.11 (cli) (built: Oct 27 2017 14:45:33) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by clue** [comment]
Hi @Dju33, have you used the search and have you seen https://github.com/reactphp/stream/issues/125?

> Without further details, it's a bit hard to diagnose this. It looks like your server is trying to write to a connection that has been closed on the client side. This it not a fatal issue and after emitting an `error` event, the server should automatically `close()` the connection.

I hope this helps :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by Flyiii** [comment]
thank you
