### ISSUE TITLE
[Question] Asynchronous I/O

### ISSUE THREAD

**Issue by slince** [reactphp/stream#136]
Hello everyone, I recently looked at the source code. i found that there are some Synchronous code, [Sync Read](https://github.com/reactphp/stream/blob/fdd0140f42805d65bf9687636503db0b326d2244/src/ReadableResourceStream.php#L135),  [Sync Write](https://github.com/reactphp/stream/blob/fdd0140f42805d65bf9687636503db0b326d2244/src/WritableResourceStream.php#L120)

this means that process is blocked when reading datagram from the kernel, event if it is very short; 

According to [Asynchronous I/O ](https://en.wikipedia.org/wiki/Asynchronous_I/O),  Reactphp seems to be non-standard.

May be we should replace  it with ` aio_write/aio_read` or `libeio/IOCP` like nodejs.

**Comment by clue** [comment]
@slince That's a very good question indeed!

As a consumer, ReactPHP provides you a number of async APIs.

Internally, ReactPHP uses a number of synchronous and asynchronous APIs, depending on use case and which APIs are available. The code you've linked uses non-blocking synchronous APIs ([1](https://github.com/reactphp/stream/blob/fdd0140f42805d65bf9687636503db0b326d2244/src/ReadableResourceStream.php#L55) and [2](https://github.com/reactphp/stream/blob/fdd0140f42805d65bf9687636503db0b326d2244/src/WritableResourceStream.php#L34)), but will only be invoked asynchronously from the event-loop (which internally uses either synchronous or asynchronous APIs depending on which event loop implementation is used). This means that this piece of code will not block and from a consumer side you will be notified through asynchronous APIs, such as the `data` event in `ReadableStreamInterface`.

This means that the current APIs are indeed asynchronous from a consumer perspective and these internals are not something most consumers have to worry about.

That being said, we continuously evaluate available APIs and may use different APIs in the future. The `aio_*` functions and family are certainly interesting, however they provide only some very limited cross platform interoperability and require APIs not available in most default PHP installations at this point in time.

I hope this helps :+1:
