### ISSUE TITLE
ReadableStreamInterface to PSR-7 StreamInterface.

### ISSUE THREAD

**Issue by bartvanhoutte** [reactphp/stream#141]
What is the best way to go from `React\Stream\ReadableStreamInterface` to `Psr\Http\Message\StreamInterface\`?

I found https://github.com/WyriHaximus/reactphp-psr7-stream-converter, but it is archived.

Thanks for your help!

**Comment by WyriHaximus** [comment]
You can buffer the contents with and once you reached the end of it create the PSR-7 request/response: https://reactphp.org/promise-stream/#buffer

**Comment by bartvanhoutte** [comment]
👌
