### ISSUE TITLE
Buffering writes when writing wouldn't block 

### ISSUE THREAD

**Issue by mbonneau** [reactphp/stream#15]
I was working on [Thruway](https://github.com/voryx/Thruway) and created a client that did non-trivial blocking I/O in response to an invocation message. While it was doing this work, more invocation messages came in and buffered on the read side of the stream. The first task completed and "wrote" to the stream. Because there is no attempt to actually write at that moment (even though it would not have blocked), the next command is read and the process begins work on that - leaving data in the write buffer until that is done (or possibly until more messages and responses are completed, depending on read-side message processing).

I was able to fix the problem by calling ```$this->handleWrite()``` immediately after ```$this->loop->addWriteStream($this->stream, [$this, 'handleWrite']);``` in Buffer.php.

I do suppose this could cause issues with handleWrite because it is possible that the write would block and get an ```EWOULDBLOCK``` error (I think), which it currently does not appear to handle.

This change also causes the unit testing to fail.
```console
1) React\Tests\Stream\BufferTest::testWriteReturnsFalseWhenBufferIsFull
Failed asserting that true is false.

/Applications/MAMP/htdocs/thruway_website/vendor/react/stream/tests/BufferTest.php:54

2) React\Tests\Stream\BufferTest::testWriteDetectsWhenOtherSideIsClosed
React\Tests\Stream\CallableStub::__invoke(RuntimeException Object (...), React\Stream\Buffer Object (...)) was not expected to be called more than once.
```

I have tried this with both StreamSelectLoop and LibEventLoop and get the same behavior. (This buffering buffers and the fix above fixes it.)

**Comment by clue** [comment]
> blocking I/O

I'm not sure it's likely we'll see support for blocking functions any time soon, given that even [the FAQs](https://github.com/reactphp/react/wiki/FAQ) warn against this (see also discussion in #16).

> I would strongly recommend that if you must "BLOCK" your server, you hand the blocking work off to another process - you should never purposefully block the event-loop. Take a look at react/child-process, fast-cgi to php-fpm or even pthreads.

:+1: on this as an alternative

Any thoughts?

**Comment by mbonneau** [comment]
To clarify: I was suggesting that write operations be attempted immediately without returning to the event-loop. If there are operations that take processing time but return data throughout the processing, it is buffered right now, waiting until control goes back to the loop before writing.

This issue is not particularly important to me, so I am going to close it.

**Comment by clue** [comment]
Thanks for your suggestion @mbonneau, it kind of looks like we talked past each other back then :-) I've just filed #54 which implements have you seem to have suggested here first :+1:
