### ISSUE TITLE
Support half-open duplex streams

### ISSUE THREAD

**Issue by clue** [reactphp/stream#27]
React PHP has support for both bidirectional duplex streams and unidirectional half-duplex streams.
- A unidirectional readable stream should `close` once it can no longer be read.
- A unidirectional writable stream should `close` once it can no longer be written to.
- A bidirectional duplex stream _currently_ `close`s once if can _either_ no longer be read or no longer be written to.

We should add an option to allow bidirectional duplex streams to be half-open. In this mode the readable and writable state would be checked independently.

This is particularly useful for some TCP/IP-based protocols where the client sends a FIN message to the server indicating that it will no longer write any data but is still willing to accept incoming data.

**Comment by clue** [comment]
For the reference, Node.js also has a [`allowHalfOpen` flag](https://nodejs.org/api/stream.html#stream_new_stream_duplex_options) which happens to default to `true`.
It's [net module](https://nodejs.org/api/net.html#net_event_end) also offers the same options which appears to default to `false`.

**Comment by nick4fake** [comment]
Just trapped into a nasty bug with old PHP version (PHP 5.5.10)

If we have write-only stream (new Stream(fopen($file, 'wb), $loop)) then stream_get_contents blocks execution even in non-blocking mode.

**Comment by clue** [comment]
@nick4fake This sounds like a separate issue (which could possibly be related to #46). Can you file a separate ticket and provide some details / a gist so I can look into this? Thanks!

**Comment by clue** [comment]
I still think that this feature makes perfect sense :+1: However, there are currently no immediate plans to build this from my end (no demand at the moment and more important outstanding issues currently), but I suppose we would be really happy to accept PRs :+1:
