### ISSUE TITLE
Code from README results in error message

### ISSUE THREAD

**Issue by ledazinha** [reactphp/stream#31]
When I try to run this code:

```php
    $loop = React\EventLoop\Factory::create();

    $source = new React\Stream\Stream(fopen('omg.txt', 'r'), $loop);
    $dest = new React\Stream\Stream(fopen('wtf.txt', 'w'), $loop);

    $source->pipe($dest);

    $loop->run();
```

I get the following error:

```
[warn] Epoll ADD(1) on fd 6 failed.  Old events were 0; read change was 1 (add); write change was 0 (none): Operation not permitted
[warn] Epoll ADD(1) on fd 7 failed.  Old events were 0; read change was 1 (add); write change was 0 (none): Operation not permitted

```

**Comment by lysenkobv** [comment]
interesting I've found here https://bugs.php.net/bug.php?id=64696
> ...the reason of the error messages is that "epoll" itself doesn't support regular files. Epoll expects whether sockets, or pipes.
> The code snippet you provided should work on OSX just fine, because Libevent chooses different polling method there.

I can't say that this is a bug of Stream, rather bug of libevent

**Comment by ledazinha** [comment]
Thanks for your answer. Yes, it appears to work more or less ok with libev, so it's probably a libevent issue.
