### ISSUE TITLE
Bindo option for stream

### ISSUE THREAD

**Issue by gamebak** [reactphp/stream#38]
Hello,
Can you add an option for the bindto inside streams/sockets ?

This is really useful when you have multiple ips and you want to use other one from the list.
.

**Comment by clue** [comment]
Hi @gamebak, looks like you're looking for https://github.com/reactphp/socket-client/issues/4.

There's a pending PR at https://github.com/reactphp/socket-client/pull/52 which is still awaiting review. This should allow you to pass the required context parameters.

**Comment by gamebak** [comment]
Thanks!
Amazing work!

2016-02-25 16:07 GMT+02:00 Christian Lück <notifications@github.com>:

**Comment by clue** [comment]
Socket options are part of the SocketClient component and available as of the [SocketClient v0.5.0 release](https://github.com/reactphp/socket-client/releases/tag/v0.5.0) :+1:
