### ISSUE TITLE
Stream Pipe not working as it is expected?

### ISSUE THREAD

**Issue by tokidoki11** [reactphp/stream#48]
So I'm creating a server (via reactphp/socket) and an SSL secureConnection(via reactphp/socket-client)

```
$creation = 0;

function create($port, $callback)
{
    global $creation;
    if ($creation == 0)
    {
        $loop = React\EventLoop\Factory::create();
        $server = new React\Socket\Server($loop);
        $server->on('connection', function ($conn)
        {
            connectFarside(function($socket) use ($conn)
            {
                $socket->pipe($conn);
                $conn->pipe($socket);
                echo "success pipe";
            });
        });

        $server->listen($port);
        $creation++;
        $callback();

        $loop->run();
    } else
    {
        $creation++;
        $callback();
    }
}

function connectFarside($callback)
{
    $loop = React\EventLoop\Factory::create();
    $tcpConnector = new React\SocketClient\TcpConnector($loop);
    $dnsResolverFactory = new React\Dns\Resolver\Factory();
    $dns = $dnsResolverFactory->createCached('8.8.8.8', $loop);


    $dnsConnector = new React\SocketClient\DnsConnector($tcpConnector, $dns);
    $secureConnector = new React\SocketClient\SecureConnector($dnsConnector, $loop, array(
        'capath' => <CAPATH>
        'local_pk' => '<PK>'
        'local_cert' => '<CERT>'
    ));

    try
    {
        $secureConnector->create('<HOST>',<PORT>)->then(function(React\Stream\Stream $stream) use ($callback)
        {
            $stream->on("error", function()
            {
                echo "SOCKET ERROR";
            });
            $callback($stream);
        }, function($err)
        {
            echo "error connect farside: ". $err;
        });

        $loop->run();
    } catch (Exception $ex)
    {
        die("lala" . $ex);
    }
    //create secure connector
}

create(60000, function()
{
});

```
The server creation and secure connection did perform successfully.
In my console I also can see "success pipe" because I'm echoing after piping the server and secure connection.

What I'm trying to do is to send an ldapquery to localhost 60000. But It seems it doesnt work.
Nothing happened.

I manage to have a nodejs code, which logically should the same here https://jsfiddle.net/L8w82rto/ . The LDAP Request did return the data for me..

I suppose there was something with the pipe?

**Comment by clue** [comment]
I'm not sure I follow your code, but it should use a single `$loop` instance and only invoke `$loop->run()` once. I hope this helps :+1:

**Comment by tokidoki11** [comment]
Hi! I have changed my code... I put the $loop outside all function all use it for all. Also use the $loop->run() once in create server function. But still, It doesnt work.

FYI, I'm trying to make somekind of proxy server. In way, I could send request to my local:60000.
Schemed like this...

MyApp Request LDAP Query  -> local:60000
local:60000 -> connected to farside server via SSL
FarsideServer -> Connected to LDAP Server

So far
1. Local:60000 has been created already, I could test it by telnet localhost 60000
2. Connection  to farside is success, I could see it estabilishing in my gateway console

As from the example in jsfiddle, Local:60000 and Farside connection stream need to be piped to each other. I'm trying to achieve this in PHP.
The code in nodejs is running fine, I could do the query to LDAP. But not the code I wrote in PHP, the query request just stuck there, blank..

Is there anyway I could help you to read my code? hehe

**Comment by clue** [comment]
The `$loop->run()` call should usually be the very last step in your script, as it will start the async event loop and will block anything else.

Can you post an updated gist of your problem?

**Comment by tokidoki11** [comment]
Hi, here is the gist link 
https://gist.github.com/tokidoki11/668a3a6f0888c05995b5f45bb2439322

I've updated the code by running `$loop->run()` at the end...
I ran php test.php then run LDAP request to by using 
`ldapsearch -x -h 127.0.0.1 -p 60000 -b <some condition>`

The php console shows `hereconnectsuccess pipe` because I echo it, but ldapsearch terminal is stuck....

**Comment by clue** [comment]
Once your proxy receives a connection, it starts a new outgoing connection and once this outgoing connection is ready, it pipes data between both connections. This means that if your client sends data to your proxy before the outgoing connection is ready, it will be discarded. You may either want to buffer your data or pause your incoming connection.

**Comment by tokidoki11** [comment]
WOAH! You're the man..
It was a success...

I've updated the gist for future references..
Thanks a lot

**Comment by clue** [comment]
Glad this helped and thanks for sharing your results with others :-) :+1:
