### ISSUE TITLE
Is 'close' a suitable name for that method?

### ISSUE THREAD

**Issue by codedokode** [reactphp/stream#82]
The name `close` doesn't imply that it would lose any data. Would not a better name be something like `cancel()`, `abort()` or `shutdown()`? 

For example, POSIX function `close()` flushes all unsaved data before closing a file descriptor.

**Comment by clue** [comment]
I agree that `close` may not be *perfect*, but I don't see any *perfect* alternative either, so how much is gained by renaming this (thus causing a BC break)?

My vote would be to first provide some better documentation so people know about its semantics and do not confuse this with the POSIX `close()` function.

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. Please come back with more details if this problem persists and we can reopen this :+1:
